## PyTorch

In [1]:
import torch

In [7]:
# number
t1 = torch.tensor(4)
t1, t1.dtype

(tensor(4), torch.int64)

In [8]:
# vector
t2 = torch.tensor([4,5.])
t2, t2.dtype

(tensor([4., 5.]), torch.float32)

In [10]:
# matrix
t3 = torch.tensor([[4,5],[5,6]])
t3, t3.dtype, t3.shape

(tensor([[4, 5],
         [5, 6]]), torch.int64, torch.Size([2, 2]))

## Tensor Operations and Gradients

In [42]:
# Create Tensors
x = torch.tensor(3)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [43]:
print("x: ",x)
print("w: ",w)
print("b: ",b)

x:  tensor(3)
w:  tensor(4., requires_grad=True)
b:  tensor(5., requires_grad=True)


In [44]:
# arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [45]:
# compute derivative
y.backward()

In [46]:
y

tensor(17., grad_fn=<AddBackward0>)

In [47]:
# display gradients 
print("dy/dx: ", x.grad) # None because it doesn't have requires_grad set to True
print("dy/dw: ", w.grad)
print("dy/db: ", b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


In [48]:
## using multi dimentional matrixs

In [49]:
# Create Tensors
x = torch.tensor([3,4])
w = torch.tensor([4.,5], requires_grad=True)
b = torch.tensor([5.,6], requires_grad=True)

In [50]:
print("x: ",x)
print("w: ",w)
print("b: ",b)

x:  tensor([3, 4])
w:  tensor([4., 5.], requires_grad=True)
b:  tensor([5., 6.], requires_grad=True)


In [51]:
w*x, b

(tensor([12., 20.], grad_fn=<MulBackward0>),
 tensor([5., 6.], requires_grad=True))

In [57]:
# arithmetic operations
y = torch.dot(w,w)
y

tensor(41., grad_fn=<DotBackward>)

In [58]:
# compute derivative
y.backward()

In [59]:
# display gradients 
print("dy/dx: ", x.grad) # None because it doesn't have requires_grad set to True
print("dy/dw: ", w.grad)
print("dy/db: ", b.grad)

dy/dx:  None
dy/dw:  tensor([ 8., 10.])
dy/db:  None


## Numpy

In [23]:
import numpy as np

In [24]:
x = np.array([[1.,2],[2,3]])
x

array([[1., 2.],
       [2., 3.]])

## convert numpy to pytorch

In [26]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [2., 3.]], dtype=torch.float64)

## convert pytorch to numpy

In [61]:
z = y.numpy()
z

array([[1., 2.],
       [2., 3.]])

## to commit notebook in jovian

In [28]:
!pip install jovian --upgrade

     |████████████████████████████████| 71kB 2.8MB/s eta 0:00:01
  Created wheel for uuid: filename=uuid-1.30-cp37-none-any.whl size=6502 sha256=75e23e5733a8cf139526b624f4a6ac739cb049641ba5ad41f9f1e2195bfacb31
  Stored in directory: /home/munna/.cache/pip/wheels/2a/80/9b/015026567c29fdffe31d91edbe7ba1b17728db79194fca1f21
Successfully built uuid


In [29]:
import jovian

<IPython.core.display.Javascript object>

In [31]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Committed successfully! https://jovian.ai/jimunna150/basic-tensor


'https://jovian.ai/jimunna150/basic-tensor'