## Learn Regression using Pytroch Builtin Library

In [3]:
import torch
import numpy as np
import torch.nn as nn

## manuallyl input 16 samples

In [16]:
# input (temp, rainfall, humidity)
inputs = np.array([
    [30,67,46],
    [40,57,56],
    [35,65,66],
    [45,63,45],
    [33,61,43],
    [36,58,46],
    [25,65,45],
    [26,53,55],
    [28,68,57],
    [30,70,48],
    [34,67,49],
    [33,66,66],
    [41,55,75],
    [24,77,43],
    [28,72,58],
    [25,75,55],
],dtype='float32'
)

# targets (apples, oranges)
targets = np.array([
    [56,70],
    [81,75],
    [76,76],
    [65,78],
    [82,65],
    [64,68],
    [67,60],
    [69,78],
    [63,73],
    [78,67],
    [49,66],
    [79,69],
    [85,77],
    [76,73],
    [70,82],
    [68,80],
    
],dtype='float32'
)

In [17]:
inputs.shape, targets.shape

((16, 3), (16, 2))

## convert np to Torch

In [18]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [19]:
list(zip(inputs, targets))

[(tensor([30., 67., 46.]), tensor([56., 70.])),
 (tensor([40., 57., 56.]), tensor([81., 75.])),
 (tensor([35., 65., 66.]), tensor([76., 76.])),
 (tensor([45., 63., 45.]), tensor([65., 78.])),
 (tensor([33., 61., 43.]), tensor([82., 65.])),
 (tensor([36., 58., 46.]), tensor([64., 68.])),
 (tensor([25., 65., 45.]), tensor([67., 60.])),
 (tensor([26., 53., 55.]), tensor([69., 78.])),
 (tensor([28., 68., 57.]), tensor([63., 73.])),
 (tensor([30., 70., 48.]), tensor([78., 67.])),
 (tensor([34., 67., 49.]), tensor([49., 66.])),
 (tensor([33., 66., 66.]), tensor([79., 69.])),
 (tensor([41., 55., 75.]), tensor([85., 77.])),
 (tensor([24., 77., 43.]), tensor([76., 73.])),
 (tensor([28., 72., 58.]), tensor([70., 82.])),
 (tensor([25., 75., 55.]), tensor([68., 80.]))]

## Dataset and Dataloader

In [20]:
from torch.utils.data import TensorDataset

In [21]:
train_dataset = TensorDataset(inputs, targets)
train_dataset

In [22]:
train_dataset[:5]

(tensor([[30., 67., 46.],
         [40., 57., 56.],
         [35., 65., 66.],
         [45., 63., 45.],
         [33., 61., 43.]]), tensor([[56., 70.],
         [81., 75.],
         [76., 76.],
         [65., 78.],
         [82., 65.]]))

In [15]:
# to use batch and random shuffiling
from torch.utils.data import DataLoader

In [24]:
batch_size = 4
train_dataloader = DataLoader(train_dataset, batch_size, shuffle=True)
train_dataloader

In [26]:
for x, y in train_dataloader:
    print("input: ",x)
    print("target: ",y)
    break

input:  tensor([[30., 67., 46.],
        [34., 67., 49.],
        [25., 65., 45.],
        [36., 58., 46.]])
target:  tensor([[56., 70.],
        [49., 66.],
        [67., 60.],
        [64., 68.]])


## Making Model

In [27]:
# model = nn.Linear(input_colum_size_per_row, target_column_size_per_row)
# model = nn.Linear((temp, rainfall, humidity), (orange, apple))
model = nn.Linear(3,2)

In [28]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1306, -0.4308,  0.4363],
        [-0.1288, -0.0896, -0.3201]], requires_grad=True)
Parameter containing:
tensor([-0.1135,  0.3457], requires_grad=True)


In [30]:
# to show the all parameters inside the model
list(model.parameters())

[Parameter containing:
 tensor([[-0.1306, -0.4308,  0.4363],
         [-0.1288, -0.0896, -0.3201]], requires_grad=True),
 Parameter containing:
 tensor([-0.1135,  0.3457], requires_grad=True)]

In [31]:
preds = model(inputs)
preds

tensor([[-12.8261, -24.2443],
        [ -5.4602, -27.8369],
        [ -3.8908, -31.1107],
        [-13.4977, -25.4973],
        [-11.9418, -23.1327],
        [ -9.7320, -24.2105],
        [-11.7479, -23.1012],
        [ -2.3451, -25.3557],
        [ -8.1963, -27.5973],
        [-13.2460, -25.1532],
        [-12.0395, -25.7196],
        [ -4.0605, -30.9427],
        [  3.5611, -33.8681],
        [-17.6601, -23.4074],
        [ -9.4833, -28.2758],
        [-11.6931, -27.1980]], grad_fn=<AddmmBackward>)

## Loss Function 

In [34]:
import torch.nn.functional as F

In [36]:
# define loss function
loss_function = F.mse_loss

In [38]:
loss = loss_function(model(inputs), targets)
loss

tensor(8129.8081, grad_fn=<MseLossBackward>)

## Optimizer

In [40]:
# Define optimizer 
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

## TO TRAIN A MODEL FOLLWED NEXT STEP
    1. Get input and target shape
    2. Define model
    3. Compute gradiant with respect to weights